### ISSUE TITLE
explodes when unable to set channel

### ISSUE THREAD

**Issue by ZeroChaos-** [deltj/kis_shootout_python#2]
halp plz

```
+ kismet_shootout -u kismet -p 036ac 036ach 036acm 036acs 036eac 050nh 051nhv2 7822UAC 7833UAC AC56 ac600m ac600m2 ac68 awus1900 cf912ac dnus81 eub1200ac intath9k N600UBE pau09 pau0a rlnknano t2u t2uh tew805ub tew809eb USB600N wdn4200 -c 6HT20
Password: 
Tuning data sources to channel 6HT20
Traceback (most recent call last):
  File "/usr/bin/kismet_shootout", line 131, in <module>
    kr.config_datasource_set_channel(source.uuid, args.channel)
  File "/usr/lib64/python3.6/site-packages/KismetRest/__init__.py", line 716, in config_datasource_set_channel
    (r, v) = self.__post_string_url("datasource/by-uuid/{}/set_channel.cmd".format(uuid), cmd)
  File "/usr/lib64/python3.6/site-packages/KismetRest/__init__.py", line 405, in __post_string_url
    raise KismetRequestException("Request failed for POST {} {}".format(url, r.status_code), r.status_code)
KismetRest.KismetRequestException: Request failed for POST datasource/by-uuid/5FE308BD-0000-0000-0000-00C0CA953EF6/set_channel.cmd 500
```

**Comment by ZeroChaos-** [comment]
this is caused by the rtl88xxau driver being unable to set a channel.  please handle failure to set channel more gracefully and maybe report which devices fail and just continue without them
